trigger: none
pool:
  vmImage: ubuntu-latest
parameters:
  - name: Arrakis
    type: string
    default: 'Arrakis'
  # storage acct name
  - name: spice
    type: string
    default: 'spice'
  # container name
  - name: container
    type: string
    default: 'tfstate'
  # tfstate file name
  - name: key
    type: string
    default: terraform.tfstate
stages:
  - stage: InitPlan
    displayName: InitPlan
    jobs:
      - job:
        displayName: 'I HAVE NO JOB'
        pool:
          name: 'Default'
        continueOnError: False
        steps:
          - task: TerraformTaskV4@4
            displayName: INIT & PLAN
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'Azure subscription 1(f33092cf-589f-4378-8f03-d8b593463157)'
              backendAzureRmResourceGroupName: ${{ parameters.Arrakis }}
              backendAzureRmStorageAccountName: ${{ parameters.spice }}
              backendAzureRmContainerName: ${{ parameters.container }}
              backendAzureRmKey: ${{ parameters.key }}
          - task: TerraformTaskV4@4
            displayName: UPGRADE
            inputs:
              provider: 'azurerm'
              displayname: init upgrade
              command: 'init'
              commandOptions: '-upgrade'
              backendServiceArm: 'Azure subscription 1(f33092cf-589f-4378-8f03-d8b593463157)'
              backendAzureRmResourceGroupName: ${{ parameters.Arrakis }}
              backendAzureRmStorageAccountName: ${{ parameters.spice }}
              backendAzureRmContainerName: ${{ parameters.container }}
              backendAzureRmKey: ${{ parameters.key }}
          - task: TerraformTaskV4@4
            displayName: VALIDATE
            inputs:
              provider: 'azurerm'
              command: 'validate'
          - task: TerraformTaskV4@4
            displayName: PLAN
            inputs:
              provider: 'azurerm'
              command: 'plan'
              commandOptions: '-lock=false'
              environmentServiceNameAzureRM: 'Azure subscription 1(f33092cf-589f-4378-8f03-d8b593463157)'
          
  - stage: Apply
    displayName: APPLY
    jobs:
      - job:
        displayName: FINAL
        pool:
          name: 'Default'
        continueOnError: False
        steps:
          - task: TerraformTaskV4@4
            displayName: FINAL INIT
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'Azure subscription 1(f33092cf-589f-4378-8f03-d8b593463157)'
              backendAzureRmResourceGroupName: ${{ parameters.Arrakis }}
              backendAzureRmStorageAccountName: ${{ parameters.spice }}
              backendAzureRmContainerName: ${{ parameters.container }}
              backendAzureRmKey: ${{ parameters.key }}
          - task: TerraformTaskV4@4
            displayName: FINAL APPLY
            inputs:
              provider: 'azurerm'
              command: 'apply'
              commandOptions: '-parallelism=20 -lock=false'
              environmentServiceNameAzureRM: 'Azure subscription 1(f33092cf-589f-4378-8f03-d8b593463157)'