trigger:
- none

pool:
  vmImage: ubuntu-latest

parameters:
  - name: Arrakis
    type: string
    default: 'Arrakis'
  - name: spice
    type: string
    default: 'spice'
  - name: container
    type: string
    default: 'tfstate'
  - name: key
    type: string
    default: terraform.tfstate

stages:
  - stage: Destroy
    displayName: DestroyResources
    jobs:
      - job:
        pool:
          name: 'Default'
        continueOnError: False
        steps:
          - task: TerraformTaskV4@4
            displayName: terraform init for destroy
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'Azure subscription 1(f33092cf-589f-4378-8f03-d8b593463157)'
              backendAzureRmResourceGroupName: ${{ parameters.Arrakis }}
              backendAzureRmStorageAccountName: ${{ parameters.spice }}
              backendAzureRmContainerName: ${{ parameters.container }}
              backendAzureRmKey: ${{ parameters.key }}
          - task: TerraformTaskV4@4
            displayName: terraform destroy
            inputs:
              provider: 'azurerm'
              command: 'destroy'
              commandOptions: '-auto-approve'
              environmentServiceNameAzureRM: 'Azure subscription 1(f33092cf-589f-4378-8f03-d8b593463157)'